SystemOrganization addCategory: #'SSH-Connections'!
SystemOrganization addCategory: #'SSH-Security'!
SystemOrganization addCategory: #'SSH-UserAuth Handshake'!
SystemOrganization addCategory: #'SSH-Transport Handshake'!
SystemOrganization addCategory: #'SSH-Msg Senders'!
SystemOrganization addCategory: #'SSH-Messages'!
SystemOrganization addCategory: #'SSH-State'!
SystemOrganization addCategory: #'SSH-Packets'!
SystemOrganization addCategory: #'SSH-Stack-Protocols'!
SystemOrganization addCategory: #'SSH-Stack-Sockets'!
