SystemOrganization addCategory: #'SSH-Connections'!
SystemOrganization addCategory: #'SSH-Handshake'!
SystemOrganization addCategory: #'SSH-Security'!
SystemOrganization addCategory: #'SSH-State'!
SystemOrganization addCategory: #'SSH-Messages'!
SystemOrganization addCategory: #'SSH-Packets'!
SystemOrganization addCategory: #'SSH-Stack-Protocols'!
SystemOrganization addCategory: #'SSH-Stack-Sockets'!
