SystemOrganization addCategory: #SSH!
SystemOrganization addCategory: 'SSH-Connections'!
SystemOrganization addCategory: 'SSH-Messages'!
SystemOrganization addCategory: 'SSH-Msg Senders'!
SystemOrganization addCategory: 'SSH-Packets'!
SystemOrganization addCategory: 'SSH-Security'!
SystemOrganization addCategory: 'SSH-Stack-Protocols'!
SystemOrganization addCategory: 'SSH-Stack-Sockets'!
SystemOrganization addCategory: 'SSH-State'!
SystemOrganization addCategory: 'SSH-Transport Handshake'!
SystemOrganization addCategory: 'SSH-UserAuth Handshake'!
