SystemOrganization addCategory: #'SSL-Cipher Suites'!
SystemOrganization addCategory: #'SSL-Connections'!
SystemOrganization addCategory: #'SSL-Encryption'!
SystemOrganization addCategory: #'SSL-Handshake Msgs'!
SystemOrganization addCategory: #'SSL-Handshake Senders'!
SystemOrganization addCategory: #'SSL-Handshake States'!
SystemOrganization addCategory: #'SSL-MAC'!
SystemOrganization addCategory: #'SSL-Messages'!
SystemOrganization addCategory: #'SSL-Records'!
SystemOrganization addCategory: #'SSL-Security'!
SystemOrganization addCategory: #'SSL-Stack-Abstract'!
SystemOrganization addCategory: #'SSL-Stack-Protocols'!
SystemOrganization addCategory: #'SSL-Stack-Sockets'!
SystemOrganization addCategory: #'SSL-State'!
SystemOrganization addCategory: #'SSL-Testing'!
SystemOrganization addCategory: #'SSL-Tools'!
